/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/_layout': RouteRecordInfo<
      '/_layout',
      '/_layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commands/': RouteRecordInfo<
      '/commands/',
      '/commands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commands/batch': RouteRecordInfo<
      '/commands/batch',
      '/commands/batch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commands/edit': RouteRecordInfo<
      '/commands/edit',
      '/commands/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commands/random-all': RouteRecordInfo<
      '/commands/random-all',
      '/commands/random-all',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/import-export': RouteRecordInfo<
      '/import-export',
      '/import-export',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/variables/': RouteRecordInfo<
      '/variables/',
      '/variables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/variables/edit': RouteRecordInfo<
      '/variables/edit',
      '/variables/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/_layout.vue': {
      routes:
        | '/_layout'
      views:
        | never
    }
    'src/views/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/views/commands/index.vue': {
      routes:
        | '/commands/'
      views:
        | never
    }
    'src/views/commands/batch.vue': {
      routes:
        | '/commands/batch'
      views:
        | never
    }
    'src/views/commands/edit.vue': {
      routes:
        | '/commands/edit'
      views:
        | never
    }
    'src/views/commands/random-all.vue': {
      routes:
        | '/commands/random-all'
      views:
        | never
    }
    'src/views/import-export.vue': {
      routes:
        | '/import-export'
      views:
        | never
    }
    'src/views/variables/index.vue': {
      routes:
        | '/variables/'
      views:
        | never
    }
    'src/views/variables/edit.vue': {
      routes:
        | '/variables/edit'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
