/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/_layout': RouteRecordInfo<'/_layout', '/_layout', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/commands/': RouteRecordInfo<'/commands/', '/commands', Record<never, never>, Record<never, never>>,
    '/commands/batch': RouteRecordInfo<'/commands/batch', '/commands/batch', Record<never, never>, Record<never, never>>,
    '/commands/edit': RouteRecordInfo<'/commands/edit', '/commands/edit', Record<never, never>, Record<never, never>>,
    '/commands/random-all': RouteRecordInfo<'/commands/random-all', '/commands/random-all', Record<never, never>, Record<never, never>>,
    '/import-export': RouteRecordInfo<'/import-export', '/import-export', Record<never, never>, Record<never, never>>,
    '/variables/': RouteRecordInfo<'/variables/', '/variables', Record<never, never>, Record<never, never>>,
    '/variables/edit': RouteRecordInfo<'/variables/edit', '/variables/edit', Record<never, never>, Record<never, never>>,
  }
}
